# Generated by Django 3.2.9 on 2021-12-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20211227_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
